{% set name = "dspy-ai" %}
{% set version = "2.4.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stanfordnlp/dspy/archive/refs/tags/{{ version }}.tar.gz
  sha256: e0327376b135ff72b16c13c989aeb5f72e34f787381fe396520d3f99b67956e1

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39 or py>311 or s390x]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - backoff >=2.2.1,<2.3
    - joblib >=1.3,<2.0
    - openai >=0.28.1,<2.0.0
    - pandas
    - regex
    - ujson
    - tqdm
    - datasets >=2.14.6,<3.0.0
    - requests
    - optuna
    - pydantic >=2.0,<3.0
    # Previous versions of structlog are missing processors.CallsiteParameterAdder
    - structlog >=22.1
    - jinja2
  run_constrained:
    - anthropic >=0.18.0,<0.19.0
    - chromadb >=0.4.14,<0.5.0
    - fastembed >=0.2.0
    - qdrant-client >=1.6.2
    - pinecone-client >=2.2.4,<2.3.0
    - weaviate-client >=4.5.4,<4.6.0
    - pymilvus >=2.3.7,<2.4.0
    - boto3 >=1.34.78,<1.35.0

test:
  source_files:
    - tests
  imports:
    - dspy
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
    - pytest-mock
    - pytorch
    - transformers

about:
  home: https://github.com/stanfordnlp/dspy
  summary: DSPy
  description: |
    DSPy: The framework for programming—not prompting—foundation models
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://dspy-docs.vercel.app/
  dev_url: https://github.com/stanfordnlp/dspy

extra:
  recipe-maintainers:
    - viridianmelody
